name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # workaround for https://github.com/marklawlor/nativewind/issues/838
          mkdir -p node_modules/.cache/nativewind/src
          touch node_modules/.cache/nativewind/src/global.css.web.css
          pnpm build
